### ISSUE TITLE
Fix the error in deleteEvent

### ISSUE THREAD

**Issue by ajaykrish244** [ajaykrish244/ScheduleBot#9]

**Comment by rrajpuro** [comment]
## Issue Update: Restructuring of Databases

After careful consideration, it has been determined that addressing this issue involves a substantial restructuring of the databases, particularly with the merging of the 'Event' and 'Event_type' entities. Due to the inherent design of the project, this won't be resolved in its current form.

The complexity of the necessary changes requires a thoughtful redesign to ensure a robust and scalable solution. We appreciate your understanding as we navigate this aspect of the project's architecture.

If you have any further questions or insights, please feel free to share. Your feedback is valuable as we work towards enhancing the overall design and functionality.

Thank you for your patience.
